conformant = "Unsupported"
notes = """
Support for TypeAliasType is not implemented.
"""
output = """
File "aliases_typealiastype.py", line 5, in <module>: typing.TypeVarTuple not supported yet [not-supported-yet]
File "aliases_typealiastype.py", line 5, in <module>: Can't find module 'typing.TypeAliasType'. [import-error]
File "aliases_typealiastype.py", line 11, in <module>: Function TypeVarTuple.__init__ expects 1 arg(s), got 2 [wrong-arg-count]
File "aliases_typealiastype.py", line 19, in <module>: Name 'GoodAlias4' is not defined [name-error]
File "aliases_typealiastype.py", line 22, in <module>: Name 'GoodAlias5' is not defined [name-error]
File "aliases_typealiastype.py", line 22, in <module>: Invalid type annotation '<instance of Tuple[nothing, ...]>'  [invalid-annotation]
File "aliases_typealiastype.py", line 46, in <module>: Name 'BadAlias4' is not defined [name-error]
File "aliases_typealiastype.py", line 47, in <module>: Name 'BadAlias5' is not defined [name-error]
File "aliases_typealiastype.py", line 48, in <module>: Name 'BadAlias7' is not defined [name-error]
"""
conformance_automated = "Fail"
errors_diff = """
Line 32: Expected 1 errors
Line 40: Expected 1 errors
Line 43: Expected 1 errors
Line 44: Expected 1 errors
Line 45: Expected 1 errors
Line 52: Expected 1 errors
Line 53: Expected 1 errors
Line 54: Expected 1 errors
Line 55: Expected 1 errors
Line 56: Expected 1 errors
Line 57: Expected 1 errors
Line 58: Expected 1 errors
Line 59: Expected 1 errors
Line 60: Expected 1 errors
Line 61: Expected 1 errors
Line 62: Expected 1 errors
Line 63: Expected 1 errors
Line 64: Expected 1 errors
Line 5: Unexpected errors ['File "aliases_typealiastype.py", line 5, in <module>: typing.TypeVarTuple not supported yet [not-supported-yet]', 'File "aliases_typealiastype.py", line 5, in <module>: Can\\'t find module \\'typing.TypeAliasType\\'. [import-error]']
Line 11: Unexpected errors ['File "aliases_typealiastype.py", line 11, in <module>: Function TypeVarTuple.__init__ expects 1 arg(s), got 2 [wrong-arg-count]']
Line 19: Unexpected errors ['File "aliases_typealiastype.py", line 19, in <module>: Name \\'GoodAlias4\\' is not defined [name-error]']
Line 22: Unexpected errors ['File "aliases_typealiastype.py", line 22, in <module>: Name \\'GoodAlias5\\' is not defined [name-error]', 'File "aliases_typealiastype.py", line 22, in <module>: Invalid type annotation \\'<instance of Tuple[nothing, ...]>\\'  [invalid-annotation]']
"""
