conformant = "Unsupported"
notes = """
Does not understand @dataclass_transform.
"""
output = """
File "dataclasses_transform_func.py", line 13, in <module>: Arguments to dataclass_transform not supported yet [not-supported-yet]
File "dataclasses_transform_func.py", line 19, in <module>: Arguments to dataclass_transform not supported yet [not-supported-yet]
File "dataclasses_transform_func.py", line 30, in create_model: bad return type [bad-return-type]
Called from (traceback):
  line 100, in current file
File "dataclasses_transform_func.py", line 30, in create_model: bad return type [bad-return-type]
File "dataclasses_transform_func.py", line 68, in <module>: Type annotation for name does not match type of assignment [annotation-type-mismatch]
File "dataclasses_transform_func.py", line 76, in <module>: Invalid keyword argument salary to function Customer1.__init__ [wrong-keyword-args]
File "dataclasses_transform_func.py", line 87, in <module>: Arguments to dataclass_transform not supported yet [not-supported-yet]
"""
conformance_automated = "Fail"
errors_diff = """
Line 72: Expected 1 errors
Line 82: Expected 1 errors
Line 111: Expected 1 errors
Lines 100, 101: Expected error (tag 'Customer3Subclass')
Line 13: Unexpected errors ['File "dataclasses_transform_func.py", line 13, in <module>: Arguments to dataclass_transform not supported yet [not-supported-yet]']
Line 19: Unexpected errors ['File "dataclasses_transform_func.py", line 19, in <module>: Arguments to dataclass_transform not supported yet [not-supported-yet]']
Line 30: Unexpected errors ['File "dataclasses_transform_func.py", line 30, in create_model: bad return type [bad-return-type]', 'File "dataclasses_transform_func.py", line 30, in create_model: bad return type [bad-return-type]']
Line 87: Unexpected errors ['File "dataclasses_transform_func.py", line 87, in <module>: Arguments to dataclass_transform not supported yet [not-supported-yet]']
"""
